deployment:
  tasks:
    - export DEPLOYPATH=/home/waileiro/cacachievershouse.org.uk/
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='.gitignore' --exclude='admin/.env.php' ./ $DEPLOYPATH