---
deployment:
  tasks:
    - export DEPLOYPATH=/home/waileiro/cacachievershouse.org.uk/
    - /usr/bin/rsync -rlptD --delete-after --exclude='.git' --exclude='.cpanel.yml' --exclude='.gitignore' ./ $DEPLOYPATH